### ISSUE TITLE
Cover consequences of leaving after early exercise before fully vested

### ISSUE THREAD

**Issue by alokmenghrajani** [jlevy/og-equity-compensation#29]
It might be worth noting that a company has the right to repurchase unvested shared if you early exercise and quit/get fired but that they won't refund any taxes paid. While early exercising can reduce your tax burden it can also increase it.

**Comment by jlevy** [comment]
Yes, agreed! We should add a point clarifying that.

**Comment by jlevy** [comment]
Expanding this to also cover the fact that the company will typically repurchase early exercised but unvested shares.
