### ISSUE TITLE
Phantom or psuedo-stock

### ISSUE THREAD

**Issue by jlevy** [jlevy/og-equity-compensation#31]
We should mention this kind of thing somewhere.

Is "phantom stock" the standard term?
See also http://www.forbes.com/sites/dking/2013/10/15/why-phantom-stock-can-be-better-than-real-stock/

From justinmk on https://news.ycombinator.com/item?id=10880726:

>The private company I work for issues stock "promises" on fancy certificates. Each certificate claims to be worth X shares for an estimated value of Y.
>Clearly they are not stock options, nor RSUs nor anything fancy or official like that. They are just fancy certificates with unverifiable claims. Is there any legal or financial value to these things? Is there a name for these types of pseudo-stocks? Where in the linked article is this discussed?

Suggested content for this topic is welcome.

**Comment by mrmcd** [comment]
re: phantom stock. 

Personally, I haven't heard of it before that comment but it sounds like from the descriptions googled up it's basically just a cash bonus that contractually defined as some multiple of the increase in stock price between the award and exercise. Presumably for public companies if the vast majority of employees are doing cashless exercises, this gives the same outcome on a cash basis of stock options but skips all the steps of actually issuing shares, collecting the strike price, and then selling them out to the market. It would keep the number of shareholders and float lower too. 

I have no idea how common this is though.

**Comment by jlevy** [comment]
Some notes from one (anonymous) person's experience with "phantom stock":

>1. The company was an S-Corp (bootstrapped -- no investors), so they had limited options for doing equity plans. This is fairly easy to set up
>2. My sense is that there is no real standard -- each random lawyer that sets it up might do it a different way
>3. When we exited, it was a huge pain to make sure that it was set up so that the money didn't get taxed twice (capital gains for the founder and then income tax for us). This is something to make sure to get right (make sure founders ask lawyer about this)
>4. No matter what you do, this is probably going to be income taxed for employees. It's pretty likely that it will be at the top rates (if you make a high salary that year and the payout is a lot)
>5. Ours had no vesting. Not sure if that's normal.
>6. Ours was set up so that we got a % of whatever the founder got, however they got it.  So, the actual acquisition had a sale-price and earn-outs over 2.5 years after acquisition and we participated in both.

**Comment by mrmcd** [comment]
So it sounds like "phantom stock" is a general catch-all term for any custom cash bonus/compensation plan based on company valuation but where no actual equity changes hands. 

A brief section with one or two real world examples would probably work for this.
