### ISSUE TITLE
What does writing a check really mean under `Exercise and hold` option?

### ISSUE THREAD

**Issue by AA33** [jlevy/og-equity-compensation#63]
Quoted from the guide:
> **Exercise and hold**: You can write the company a check and pay any taxes on the spread. You are then a stockholder, with a stock certificate that may have value in the future. As discussed above, you may do this “early”, even immediately upon grant, before vesting (if early exercise is available to you), sometime after vesting, or after leaving the company, as long as the exercise window is open. Recall that often the window closes soon after you leave a company, e.g. 90 days after termination.

**Can the company encash the check at any time?** 
If yes, then why is this a good option to take for stock options that have not even vested and may not even be worth much even after vesting? The check itself could be of a significant amount and there may be taxes to pay even after that.

**OR**

Does it have to be done solely for the sake of agreement over the transfer of stock and only in special circumstances the check will be encashed?
If this case, what are the special circumstances involved here?
Should an employee seek such an agreement in writing before handing over the check?

**Comment by kspaans** [comment]
In this context "writing a check" means to literally pay the company, right away. If you paid with a check, the company would cash it. They will have the money, and you will have the stock. The advantage to you is you now own the stock. One potential advantage of exercising your options as soon as possible is the long-term capital gains tax rate.
