### ISSUE TITLE
Discuss authorized vs issued shares

### ISSUE THREAD

**Issue by jlevy** [jlevy/og-equity-compensation#8]
Discuss how authorized shares differ from issued shares, and are essentially meaningless. Also mention when/how numbers that appear in official paperwork are for authorized.

**Comment by joewallin** [comment]
I added a discussion of this under Stock.

**Comment by jlevy** [comment]
:+1:
Perhaps also worth mentioning why authorized shares are a larger number in the first place?
And that it's authorized shares that are likely to appear in corporate filings etc?
Also, any good links on this?
